export const items: Record<string, string> = {
  "Recombobulator 3000": "RECOMBOBULATOR_3000",
  "Bonzo's Staff": "BONZO_STAFF",
  "Fuming Potato Book": "FUMING_POTATO_BOOK",
  "Bonzo's Mask": "BONZO_MASK",
  "Red Nose": "RED_NOSE",
  "Hot Potato Book": "HOT_POTATO_BOOK",
  "Enchanted Book (No Pain No Gain 1)":
    "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-1",
  "Enchanted Book (No Pain No Gain 2)":
    "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-2",
  "Enchanted Book (Ultimate Jerry 1)": "ENCHANTED_BOOK-ULTIMATE_JERRY-1",
  "Enchanted Book (Ultimate Jerry 2)": "ENCHANTED_BOOK-ULTIMATE_JERRY-2",
  "Enchanted Book (Ultimate Jerry 3)": "ENCHANTED_BOOK-ULTIMATE_JERRY-3",
  "Enchanted Book (Bank 1)": "ENCHANTED_BOOK-ULTIMATE_BANK-1",
  "Enchanted Book (Bank 2)": "ENCHANTED_BOOK-ULTIMATE_BANK-2",
  "Enchanted Book (Bank 3)": "ENCHANTED_BOOK-ULTIMATE_BANK-3",
  "Enchanted Book (One For All 1)": "ENCHANTED_BOOK-ULTIMATE_ONE_FOR_ALL-1",
  "Enchanted Book (Soul Eater 1)": "ENCHANTED_BOOK-ULTIMATE_SOUL_EATER-1",
  "Enchanted Book (Combo 1)": "ENCHANTED_BOOK-ULTIMATE_COMBO-1",
  "Enchanted Book (Combo 2)": "ENCHANTED_BOOK-ULTIMATE_COMBO-2",
  "Enchanted Book (Infinite Quiver 6)": "ENCHANTED_BOOK-INFINITE_QUIVER-6",
  "Enchanted Book (Infinite Quiver 7)": "ENCHANTED_BOOK-INFINITE_QUIVER-7",
  "Enchanted Book (Feather Falling 6)": "ENCHANTED_BOOK-FEATHER_FALLING-6",
  "Enchanted Book (Feather Falling 7)": "ENCHANTED_BOOK-FEATHER_FALLING-7",
  "Enchanted Book (Rejuvenate 1)": "ENCHANTED_BOOK-REJUVENATE-1",
  "Enchanted Book (Rejuvenate 2)": "ENCHANTED_BOOK-REJUVENATE-2",
  "Enchanted Book (Rejuvenate 3)": "ENCHANTED_BOOK-REJUVENATE-3",
  "Enchanted Book (Ultimate Wise 1)": "ENCHANTED_BOOK-ULTIMATE_WISE-1",
  "Enchanted Book (Ultimate Wise 2)": "ENCHANTED_BOOK-ULTIMATE_WISE-2",
  "Enchanted Book (Wisdom 1)": "ENCHANTED_BOOK-ULTIMATE_WISDOM-1",
  "Enchanted Book (Wisdom 2)": "ENCHANTED_BOOK-ULTIMATE_WISDOM-2",
  "Enchanted Book (Last Stand 1)": "ENCHANTED_BOOK-ULTIMATE_LAST_STAND-1",
  "Enchanted Book (Last Stand 2)": "ENCHANTED_BOOK-ULTIMATE_LAST_STAND-2",
  "Enchanted Book (Rend 1)": "ENCHANTED_BOOK-ULTIMATE_REND-1",
  "Enchanted Book (Rend 2)": "ENCHANTED_BOOK-ULTIMATE_REND-2",
  "Spirit Bone": "SPIRIT_BONE",
  "Spirit Wing": "SPIRIT_WING",
  "Enchanted Book (Thunderlord 7)": "ENCHANTED_BOOK-THUNDERLORD-7",
  "Suspicious Vial": "SUSPICIOUS_VIAL",
  "Dark Claymore": "DARK_CLAYMORE",
  "Necron Dye": "DYE_NECRON",
  "Livid Dye": "DYE_LIVID",
  "Master Skull - Tier 1": "MASTER_SKULL_TIER_1",
  "Master Skull - Tier 2": "MASTER_SKULL_TIER_2",
  "Master Skull - Tier 3": "MASTER_SKULL_TIER_3",
  "Master Skull - Tier 4": "MASTER_SKULL_TIER_4",
  "Master Skull - Tier 5": "MASTER_SKULL_TIER_5",
  "First Master Star": "FIRST_MASTER_STAR",
  "Second Master Star": "SECOND_MASTER_STAR",
  "Third Master Star": "THIRD_MASTER_STAR",
  "Fourth Master Star": "FOURTH_MASTER_STAR",
  "Fifth Master Star": "FIFTH_MASTER_STAR",
  "Necron's Handle": "NECRON_HANDLE",
  "Necromancer's Brooch": "NECROMANCER_BROOCH",
  "Adaptive Blade": "STONE_BLADE",
  "Adaptive Boots": "ADAPTIVE_BOOTS",
  "Adaptive Leggings": "ADAPTIVE_LEGGINGS",
  "Adaptive Chestplate": "ADAPTIVE_CHESTPLATE",
  "Adaptive Helmet": "ADAPTIVE_HELMET",
  "Adaptive Belt": "ADAPTIVE_BELT",
  "Red Scarf": "RED_SCARF",
  "Scarf's Studies": "SCARF_STUDIES",
  "Legendary Spirit Pet": "PET-SPIRIT-LEGENDARY",
  "Epic Spirit Pet": "PET-SPIRIT-EPIC",
  "Spirit Shortbow": "ITEM_SPIRIT_BOW",
  "Spirit Sword": "SPIRIT_SWORD",
  "Spirit Mask": "SPIRIT_MASK",
  "Spirit Boots": "THORNS_BOOTS",
  "Spirit Stone": "SPIRIT_DECOY",
  "Wither Boots": "WITHER_BOOTS",
  "Wither Helmet": "WITHER_HELMET",
  "Wither Chestplate": "WITHER_CHESTPLATE",
  "Wither Leggings": "WITHER_LEGGINGS",
  "Wither Catalyst": "WITHER_CATALYST",
  "Precursor Gear": "PRECURSOR_GEAR",
  "Wither Cloak Sword": "WITHER_CLOAK",
  "Wither Blood": "WITHER_BLOOD",
  Implosion: "IMPLOSION_SCROLL",
  "Shadow Warp": "SHADOW_WARP_SCROLL",
  "Wither Shield": "WITHER_SHIELD_SCROLL",
  "Auto Recombobulator": "AUTO_RECOMBOBULATOR",
  "Maxor the Fish": "MAXOR_THE_FISH",
  "Goldor the Fish": "GOLDOR_THE_FISH",
  "Storm the Fish": "STORM_THE_FISH",
  "Precursor Eye": "PRECURSOR_EYE",
  "Giant's Sword": "GIANTS_SWORD",
  "Necromancer Lord Chestplate": "NECROMANCER_LORD_CHESTPLATE",
  "Summoning Ring": "SUMMONING_RING",
  "Necromancer Sword": "NECROMANCER_SWORD",
  "Necromancer Lord Leggings": "NECROMANCER_LORD_LEGGINGS",
  "Necromancer Lord Helmet": "NECROMANCER_LORD_HELMET",
  "Sadan's Brooch": "SADAN_BROOCH",
  "Necromancer Lord Boots": "NECROMANCER_LORD_BOOTS",
  "Enchanted Book (Swarm 1)": "ENCHANTED_BOOK-ULTIMATE_SWARM-1",
  "Giant Tooth": "GIANT_TOOTH",
  "Dark Orb": "DARK_ORB",
  "Enchanted Book (Lethality 6)": "ENCHANTED_BOOK-LETHALITY-6",
  "Enchanted Book (Overload 1)": "ENCHANTED_BOOK-OVERLOAD-1",
  "Enchanted Book (Legion 1)": "ENCHANTED_BOOK-ULTIMATE_LEGION-1",
  "Shadow Fury": "SHADOW_FURY",
  "Last Breath": "LAST_BREATH",
  "Shadow Assassin Chestplate": "SHADOW_ASSASSIN_CHESTPLATE",
  "Livid Dagger": "LIVID_DAGGER",
  "Shadow Assassin Leggings": "SHADOW_ASSASSIN_LEGGINGS",
  "Warped Stone": "AOTE_STONE",
  "Shadow Assassin Helmet": "SHADOW_ASSASSIN_HELMET",
  "Shadow Assassin Boots": "SHADOW_ASSASSIN_BOOTS",
  "Kismet Feather": "KISMET_FEATHER",
  "Balloon Snake": "BALLOON_SNAKE",
  "Shadow Assassin Cloak": "SHADOW_ASSASSIN_CLOAK",
  "Soulweaver Gloves": "SOULWEAVER_GLOVES",
  "Fel Skull": "FEL_SKULL",
  "Bonzo Shard": "SHARD_BONZO",
  "Scarf Shard": "SHARD_SCARF",
  "Thorn Shard": "SHARD_THORN",
  "Wither Shard": "SHARD_WITHER",
  "Apex Dragon Shard": "SHARD_APEX_DRAGON",
  "Power Dragon Shard": "SHARD_POWER_DRAGON",
};